---
title: "Canadian Teachers by Sex"
author: "John Menzies"
format: html
execute: 
  echo: false
---


```{r}
#| label: setup
#| message: false
library(tidyverse)
library(stringr)
```

```{r}
#| label: data-load
#| message: false
df <- read_csv("./data/14100022-eng/14100022.csv")
df <- janitor::clean_names(df)
```


```{r}
#| label: graphic
df |> 
  filter(
    geo == "Canada",
    labour_force_characteristics == "Labour force",
    age_group == "15 years and over",
    uom == "Persons",
    sex != "Both sexes",
    str_detect(north_american_industry_classification_system_naics, "Education")
  ) |> 
  mutate(ref_date = ym(ref_date) )|> 
  ggplot(aes(x = ref_date, y = value, fill = sex)) +
  geom_area(position = "stack", alpha = 0.6) +  # Stacked area plot
  geom_line(position = "stack", aes(color = sex), linewidth = 1) +  # Line plot
  labs(
    title = "Employment in Educational Services in Canada by Sex",
    x = "Date",
    y = "People employed over the age of 15, thousand people",
    fill = "Sex",
    color = "Sex"
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


```